# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias desc='cd "C:\Users\Alexei\Desktop"'
alias desc_e='cd "C:\Users\Alexei\Desktop" && explorer .'
alias subl_path='cd "C:\Users\Alexei\AppData\Roaming\Sublime Text 3\Packages\User"'
alias subl_path_e='cd "C:\Users\Alexei\AppData\Roaming\Sublime Text 3\Packages\User" && explorer .'
alias exer_path='cd "D:\Programming\my-exercism-exercises\javascript"'
alias exer_path_e='cd "D:\Programming\my-exercism-exercises\javascript" && explorer .'

#n pm list only top level modules.
alias ng="npm list -g --depth=0 2>/dev/null"
alias nl="npm list --depth=0 2>/dev/null"


